name: assignment1deploy

on:
    push:
        paths:
            - 'assignment1/**'
    
jobs:
    assignment1:
        runs-on: ubuntu-latest

        name: Assignment 1
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            WORKING_DIR: ./assignment1
        environment: workflowSetup
        steps:
            - uses: actions/checkout@v3

            - name: 'Init terraform'
              id: init
              run: terraform init
              working-directory: ${{ env.WORKING_DIR }}

            - name: 'Terraform plan'
              id: plan
              run: terraform plan -var="kv_secret_login_username=${{secrets.KV_USERNAME}}" -var="kv_secret_login_password=${{secrets.KV_PASSWORD}}" -var="security_rule_dest_port=${{secrets.PORT_NR}}" -var="security_rule_source_address=${{secrets.IP_ADDRESS}}" -out main.tfplan
              working-directory: ${{ env.WORKING_DIR }}

            - name: 'Check last commit message'
              id: commit
              run: echo "::set-output name=message::$(git log --format=%B -n 1)"
              working-directory: ${{ env.WORKING_DIR }}

            - name : 'Terraform apply or destroy'
              id: applydestroy
              run: |
                if [[  "${{ steps.commit.outputs.message }}" == *"destroy"* ]]; then
                  terraform destroy -auto-approve
                else
                  terraform apply -auto-approve
                fi  
              working-directory: ${{ env.WORKING_DIR }}

        